### ISSUE TITLE
Clarification around Not Installing TWRP to the Slot You Want PmOS On

### ISSUE THREAD

**Issue by 4tuw2tuv0** [calebccff/pmos-oneplus6#3]
The README warns that "You can NOT install TWRP or any custom recovery on the slot running postmarketOS, it will not boot due to modifications made by the installer, it will also break postmarketOS." but, as far as I understand things (i.e. have Googled), the most recent version of TWRP for both the OnePlus 6 and 6T installs to both slots, without consulting beforehand.

Am I misunderstanding something (very possible)? Or is this just saying to never install TWRP since there's no way to do so without, in turn, installing to the slot you'll, eventually, put PmOS on?

**Comment by kcxt** [comment]
The way that custom recoveries work on system-as-root devices like the OnePlus 6, is that the recovery *is* the initramfs, were on older devices the initramfs was used to boot android and the recovery initramfs would be on a separate partition.

PostmarketOS is not android and just uses an initramfs in the same way any normal Linux distro would. This means that if you flash the TWRP installer it will nuke the initramfs on both slots, this is fine for android but means that instead of booting PostmarketOS the device will attempt to run TWRP on the mainline kernel. This will result in your device not booting.

If you want to install TWRP, you can just backup the PostmarketOS boot partition and reflash it afterwards.

Hopefully this answers your questions.

**Comment by 4tuw2tuv0** [comment]
Interesting; thanks a ton – it's definitely informative.

So does that mean you could, theoretically, just install TWRP before installing PmOS and install PmOS after that?

I'd done that, yesterday, and had been able to boot PmOS; but the way the README's worded, I hadn't realized that might even be an option (perhaps it's the only logical conclusion, based off of how things work, but, without the info. you just provided me, it seemed like it was saying that I shouldn't install TWRP to that slot, at any point, if I wanted to ever install PmOS to it).

**Comment by kcxt** [comment]
It's useful to be aware of what "installing TWRP" actually means, and apply some common sense here. PostmarketOS does not know about, care about, or depend on anything related to Android. It's an important distinction to make as we aren't running any downstream / vendor code here.

I see where your misconceptions might arise regarding the wording, realistically if you're attempting to run PostmarketOS on your device it's advisable that you have a solid understanding of how Android devices boot and work in general.

I'm more than happy to accept pull requests if you want to improve the wording.

Beyond being able to dual boot android and PostmarketOS, I dont intend to offer any extra support or guidance on how to e.g. flash TWRP. Closing this as out of scope in that respect.
